#ifndef DEFINES_h
#define DEFINES_h

#define MAX_POSSIBLE_BASE_QUAL 41
#define MAX_POSSIBLE_MAP_QUAL 70
#define MAX_FEASIBLE_UMI_EDIT_DISTANCE 3
#define MIN_POSSIBLE_CON_SIZE 2
#define MAX_POSSIBLE_PAD_LENGTH 250

#define MAX_NM 15
#define MAX_READ_LEN 150 
#define MAX_INTERVAL_LEN 13000
#define MAX_INSERT_RANGE 1000
#define VEC_SIZE 25000
#define CLUSTER_LEN 10

//#define DEBUG

#endif

